version: 3.9.{build}
image: Visual Studio 2017

build_script:
  - ps: .\build.ps1 -Target "Appveyor"

# disable built-in tests.
test: off

# Holds the build machine open and displays information on how to RDP into the box.
# Useful for figuring out why your builds are not working, but comment out when you are done :)
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))